### ISSUE TITLE
Useless @inbounds

### ISSUE THREAD

**Issue by jlapeyre** [QuanEstimation/QuanEstimation.jl#48]
`@inbounds` wraps an entire block. So adding `@inbounds` to the outermost of nested loops disables bounds checking inside all loops. So, you only need the first `@inbounds` here.
https://github.com/QuanEstimation/QuanEstimation.jl/blob/5ab636a46cc2615f9f91647a0bc4f89a05fd5930/src/Parameterization/Lindblad/LindbladDynamics.jl#L32-L39

In fact, people usually recommend making the scope as small as possible. So you could keep the fourth `@inbounds` counting from the top and remove all others. The resulting compiled code would be exactly the same as you have now.
```julia
    for i = 1:dim
        for j = 1:dim
            ni = dim * (i - 1) + j
            for k = 1:dim
                @inbounds for l = 1:dim
                    nj = dim * (k - 1) + l
                    L_temp = A[i, k] * conj(A[j, l])
                    for p = 1:dim
                        L_temp -=
                            0.5 * float(k == i) * A[p, j] * conj(A[p, l]) +
                            0.5 * float(l == j) * A[p, k] * conj(A[p, i])
                    end
                    result[ni, nj] = L_temp
                end
            end
        end
    end
```

**Comment by HM-Yuuu** [comment]
Thanks for pointing this out, we will fix it.
