### ISSUE TITLE
non-concrete fields in `struct`s are considered harmful

### ISSUE THREAD

**Issue by jlapeyre** [QuanEstimation/QuanEstimation.jl#49]
`epsilon` here should be a concrete type
https://github.com/QuanEstimation/QuanEstimation.jl/blob/5ab636a46cc2615f9f91647a0bc4f89a05fd5930/src/Algorithm/Algorithm.jl#L5-L8

There are many other similar `struct`s in the code. See [the doc on this](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-type).

Something like this is better
```julia
 struct GRAPE{T<:Number} <: AbstractGRAPE 
     max_episode::Int  
     epsilon::T
 end 
```
This allows the compiler to infer types in more situations. It also makes a more efficient layout.

The following line is in a tight loop and the type of `epsilon` is not known to the compiler. (I'm fairly sure, but could be missing something.) This means the code is probably not optimized for, say `Float64`.

https://github.com/QuanEstimation/QuanEstimation.jl/blob/5ab636a46cc2615f9f91647a0bc4f89a05fd5930/src/Algorithm/GRAPE.jl#L202

**Comment by HM-Yuuu** [comment]
I think you are correct, and thanks for the comments!
We will recheck our codes and replace all the abstract types that may be harmful to the performance with concrete ones using the parametric constructor layout.
